### PR TITLE
Add TFRs

### PR DESCRIPTION
**Pull request by dziban303**
This PR adds TFRs to the map. To do so, EndOfHead.html is modified to add the `tfrs.geojson` file, EndOfBody.html is modified to add the button (and do some general cleanup), and add a script to pull and format the TFRs from airframesio's GH repo. 

The script still needs some work—like the backup function can be removed—and a finished script would need to be accommodated by @76rhodan to run periodically (daily probably) to update the TFRs. 

image

### CODE REVIEW

**Comment by 76rhodan** [comment]
So, I just need to replace the two html, put the geojson in place and add a bit of update magic from the included script to get this running?

**Comment by rikgale** [comment]
Any idea how I would merge this into a different branch? I have set up a tfrs branch so I can test this out. Also is this world wide or US only?

**Comment by 76rhodan** [comment]
There should be an edit button on the right beside the title of the PR. If you click on it, you can choose a different branch to merge the PR into.

image

image

**Comment by rikgale** [comment]
Pulled. I will have a play over the weekend

**Pull request merged**
